- name: "Hosts"
  hosts: all
  become: yes

  tasks:
   - name: "Vault | Generate RSA Key"
     command: openssl genrsa \
      -out "/docker-compose/vault/build-vault/key.pem" 2048
     args:
      creates: "/docker-compose/vault/build-vault/key.pem"

   - name: "Vault | Generate CSR"
     command: openssl req \
      -new \
      -subj '/C=BR/ST=SP/L=Sao Paulo/O=TGL/CN={{ fqdn }}'
      -key "/docker-compose/vault/build-vault/key.pem" \
      -out "/docker-compose/vault/build-vault/csr.pem"
     args:
      creates: "/docker-compose/vault/build-vault/csr.pem"

   - name: "Vault | Generate Self-signed Certificate"
     command: openssl req \
      -x509 \
      -days 1825 \
      -key "/docker-compose/vault/build-vault/key.pem" \
      -in "/docker-compose/vault/build-vault/csr.pem" \
      -out "/docker-compose/vault/build-vault/cert.pem"
     args:
      creates: "/docker-compose/vault/build-vault/cert.pem"

   - name: "Vault | Verify certificate crt"
     shell: openssl x509 -noout -modulus -in /docker-compose/vault/ssl/cert.pem | openssl md5
     register: crt
     tags: check_crt
   - debug: var=crt.stdout_lines
     tags: check_crt

   - name: "Vault | Verify certificate key"
     shell: openssl rsa -noout -modulus -in /docker-compose/vault/ssl/key.pem| openssl md5
     register: crt
     tags: check_key
   - debug: var=crt.stdout_lines
     tags: check_key
